spring:
  datasource:
    url: jdbc:h2:mem:my_db
    username: user
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
#    console.path: /h2-console